### ISSUE TITLE
Получение CLIENT_SECRET

### ISSUE THREAD

**Issue by azhiv** [valiotti/get-receipts#2]
Подскажите - каким образом можно получить CLIENT_SECRET?

**Comment by aeksei** [comment]
@azhiv Алгоритм генерации CLIENT_SECRET не ясен((( Для разных учетных записей на разных iOS устройствах он одинаков. Возможно для Android устройств он другой. 
Если хотите получить CLIENT_SECRET, вам нужно перехватить и расшифровать HTTPS трафик от вашего устройства. И там в момент авторизации от устройства передается JSON, который содержит CLIENT_SECRET, и позволяет авторизовать устройство. Есть предположение, что CLIENT_SECRET авторизует не пользователя, а предоставляет доступ к API.

Если нужна подробная информация по получению доступа к HTTPS трафику можете написать мне на почту либо в телеграмм @aeksei, там можем детально обсудить этот вопрос

**Comment by sasha127** [comment]
@azhiv @aeksei приветствую! Алгоритм получения client_secret теперь известен. Подробнее в [этом обсуждении](https://github.com/DmitriyBobrovskiy/CheckReceiptSDK/issues/12).
